### ISSUE TITLE
Undefined constant "request"

### ISSUE THREAD

**Issue by Rudnev** [swoole/yasd#172]
Remote debugging via PhpStorm. After successfully reaching the first breakpoint and after sending any next command (for example "step over") the script ends with an error:

```
[2022-08-16 06:35:21 *19.1]     TRACE   http_request_message_complete(:814): request body length=0
[2022-08-16 06:35:21 *19.1]     TRACE   Context::Context(:53): alloc stack: size=2097152, ptr=0x7f8520798010
[2022-08-16 06:35:21 *19.1]     TRACE   PHPCoroutine::main_func(:761): Create coro id: 1, origin cid: -1, coro total count: 1, heap size: 1822032
[2022-08-16 06:35:21 #1.4]      TRACE   Timer::select(:196): timer msec=10000, round=11
[2022-08-16 06:35:21 #1.4]      TRACE   Timer::select(:206): id=1, exec_msec=10000, round=0, exist=0
[2022-08-16 06:35:22 #1.4]      TRACE   Timer::select(:196): timer msec=11001, round=12
[2022-08-16 06:35:22 #1.4]      TRACE   Timer::select(:206): id=1, exec_msec=11000, round=0, exist=0
[2022-08-16 06:35:23 *19.1]     TRACE   ProcessFactory::finish(:241): worker_id=1, type=2

Fatal error: Uncaught Error: Undefined constant "request" in yasd://debug-eval:1
Stack trace:
#0 /var/www/server.php(6): unknown()
#1 [internal function]: {closure}(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#2 {main}
  thrown in yasd://debug-eval on line 1
[2022-08-16 06:35:23 *19.1]     TRACE   PHPCoroutine::on_yield(:604): from cid=1 to cid=-1
[2022-08-16 06:35:23 #1.1]      TRACE   Socket::send(:751): send 167/167 bytes, errno=11
[2022-08-16 06:35:23 *19.1]     TRACE   ReactorEpoll::del(:128): remove event[reactor_id=0|fd=15]
[2022-08-16 06:35:23 *19.1]     ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Error: Undefined constant "request" in yasd://debug-eval:1
Stack trace:
#0 /var/www/server.php(6): unknown()
#1 [internal function]: {closure}(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#2 {main}
  thrown in yasd://debug-eval on line 1
[2022-08-16 06:35:23 $13.0]     WARNING Server::check_worker_exit_status(): worker(pid=19, id=1) abnormal exit, status=255, signal=0
```
**PHP**: 8.1
**Swool:** 4.8.11, 5.0.0, master
**Yasd:** master

server.php:
```php
$http = new Swoole\Http\Server("0.0.0.0", 80);

$http->on("request", function ($request, $response) {
    $response->end("Hello, World!"); // breakpoint
});

$http->start();
```
**Docker environment to reproduce**:

Dockerfile:
```dockerfile
FROM phpswoole/swoole:5.0-php8.1-dev

RUN apt-get update \
    && apt-get install -y libboost-all-dev \
    && cd /tmp && curl -SL "https://github.com/swoole/yasd/archive/refs/heads/master.tar.gz" -o yasd.tar.gz \
    && mkdir -p yasd \
    && tar -xf yasd.tar.gz -C yasd --strip-components=1 \
    && ( \
        cd yasd \
        && phpize \
        && ./configure \
        && make && make install \
    ) \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN echo "zend_extension=yasd" > /usr/local/etc/php/conf.d/yasd.ini \
    && echo "yasd.debug_mode=remote" >> /usr/local/etc/php/conf.d/yasd.ini \
    && echo "yasd.remote_host=host.docker.internal" >> /usr/local/etc/php/conf.d/yasd.ini \
    && echo "yasd.remote_port=9003" >> /usr/local/etc/php/conf.d/yasd.ini
```
docker-compose.yml:
```yaml
version: '3'

services:
  swoole:
    build:
      dockerfile: Dockerfile
    ports:
      - '80:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PHP_IDE_CONFIG: 'serverName=localhost'
    volumes:
      - '.:/var/www'
    networks:
      - default
    command:
      - 'php -e server.php'

networks:
  default:
    driver: bridge
```

**Comment by Rudnev** [comment]
There are differences between Yasd and Xdebug DBGP messages:
```php
$foo = new stdClass();
echo 'breakpoint';
```
Xdebug:
```
context_get -i 18 -d 0 -c 0
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="context_get" transaction_id="18" context="0"><property name="$foo" fullname="$foo" type="object" classname="stdClass" children="0" numchildren="0" page="0" pagesize="100"></property></response>

```
Yasd:

```
context_get -i 18 -d 0 -c 0
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="context_get" transaction_id="18" context="0"><property type="object" name="$foo" fullname="foo" classname="stdClass" children="0" numchildren="0"/></response>
```

It looks like the `fullname` attribute must contain the `$` character because PhpStorm uses this attribute in the next command:

```
eval -i 21 -- KHN0cmluZykoZm9vKQ== // decoded value is "(string)(foo)"
```
This command is sent if enabled `__toString` object view in the debug settings (enabled by default).

**Comment by florianmischler** [comment]
i have the same issues but slightly different:
- Undefined constant "this"
- Undefined constant "cacheTable"
and so on...
but only when i want to debug with phpStorm (2022.2.3) - running the application without listening to the ide is fine
breakpoint recognition is fine but at some point in the code when i want to step over or into i get these exceptions (same as @Rudnev )

screenshot during exception in phpStorm
![Screenshot 2022-11-17 at 09 26 58](https://user-images.githubusercontent.com/26787129/202399864-edb43e0e-e4a2-4de5-bb25-0922a2554554.png)

the postman request i am testing with
<img width="449" alt="Screenshot 2022-11-17 at 09 28 24" src="https://user-images.githubusercontent.com/26787129/202399887-2bb6c792-2f1d-449b-b441-0d34df7970b9.png">



**Environment:**
Docker
- FROM phpswoole/swoole:5.0-php8.0-alpine
-- exact alpine version 3.16
-- exact php version 8.0.21
- YASD 0.3.9 (release)
- Laravel 9.26.1
-- Octane + Swoole
-- Sail


**php.ini for development**
```
[PHP]
post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS

[yasd]
zend_extension = yasd
xdebug.coverage_enable = 1
xdebug.idekey = glorp
xdebug.profiler_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_connect_back = 1
xdebug.remote_mode = req
yasd.debug_mode = remote
yasd.depth = 1
yasd.log_level = -1
yasd.max_executed_opline_num = 50000
yasd.open_extended_info = 1
yasd.remote_host = host.docker.internal
yasd.remote_port = 9003
```



**run-octane.sh - which is executed via supervisord**
```
//YASD NOTED: if Swoole\Server, set the worker_num to 1, otherwise the breakpoint may fail.
php artisan octane:start --server=swoole --host=0.0.0.0 --workers=1 --task-workers=1 --port=8201 --watch || fail "atma octane fail"
```

**Comment by huanghantao** [comment]
Can consider to use https://github.com/swoole/swoole-src/tree/support-xdebug
You can use xdebug directly, as long as the PHP version is 8.1 or greater
